# -*- coding: utf-8 -*-
"""Taylor Swift Discography

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMa_4rJdiHsiFqe9vzL0jI3aD7kQwsgX

The clean finished version
"""

#json file creation

!pip install spotipy

import spotipy
from spotipy import SpotifyClientCredentials
#from decouple import config

# This section is where the Spotify API is called
import os
client_id = os.getenv("SPOTIFY_CLIENT_ID")
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")
auth = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
client = spotipy.Spotify(client_credentials_manager=auth)

# This section is where the dataset's root is created
dataset_ = list()

# Here you can put any artist's link to create a dataset
artist = "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
artist_uri = artist.split("/")[-1].split("?")[0]
albums = client.artist_albums(artist_uri)['items']
artist_name = albums[0]['artists'][0]['name']

# Here I selected the most important attributes of tracks and albums. You can change according to your preference
for album in albums:
    album_id = album['id']
    album_uri = album['uri']
    album_name = album['name']
    album_img = album['images'][0]['url']
    album_year = album['release_date']
    album_popularity = 0
    tracks = client.album_tracks(album_uri)['items']
    for index, _ in enumerate(tracks):
        track_id = tracks[index]['id']
        track_name = tracks[index]['name']
        track_features = client.audio_features(track_id)[0]
        dictionary = dict()
        dictionary["artist_name"] = artist_name
        dictionary["album_name"] = album_name
        dictionary["album_img"] = album_img
        dictionary["album_year"] = album_year
        dictionary["track_name"] = track_name
        dictionary["track_id"] = index

        dataset_.append(dictionary)

# This section is where json files are named
json_archive = f'{artist_name.split()[0].lower()}_{artist_name.split()[0].lower()}_project.json'

# This section is where the album release year is converted to an integer
for data in dataset_:
    data["album_year"] = int(data["album_year"][0:4])

# This is the final dataset
dataset = dataset_


import json
#from create_dataset
#import dataset, json_archive


# This is where you create a json file
with open(json_archive, 'w') as archive:
    archive.write("[")
    for index, data in enumerate(dataset):
        archive.write(json.dumps(data, indent=4))
        if not index == len(dataset) - 1:
            archive.write(",\n")
    archive.write("]")

#image download

#midnights3am
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273e0b60c608586d88252b8fbc0" -O "Midnights (3am Edition).jpg"
#Reputation Karaoke Version
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273c288028c2592f400dd0b9233" -O "Taylor Swift Karaoke: reputation.jpg"
#Lover
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273c288028c2592f400dd0b9233" -O "Lover"
#folklore: the long pond sessions
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273045514e3ed4e1767a7c3ece5" -O "folklore: the long pond studio sessions (from the Disney+ special)[deluxe edition].jpg"
#Folklore
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273c288028c2592f400dd0b9233" -O "folklore (deluxe version).jpg"
#Evermore
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b27390fd9741e1838115cd90b3b6" -O "evermore (deluxe version).jpg"
#Fearless (Taylors Version)
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273318443aab3531a0558e79a4d" -O "Fearless (Taylor's Version).jpg"
#Red (Taylors Version)
!wget -e robots=off "https://i.scdn.co/image/ab67616d0000b273318443aab3531a0558e79a4d" -O "Red (Taylor's Version).jpg"

#Creating the keywords list for the search

!pip install ipyplot
import re
import time
import random
import ipyplot
with open('taylor_taylor_project.json') as f:
  d = json.load(f)

keywords_list = []

for r in d:
  keywords_list.append([r['album_name'],r['track_name']])
  print(keywords_list)

def keyword_collection(d):
    for r in d:
      for n in r['artist_name']:
        keywords_list.append([r['album_name'], n['album_name']])
    print(keywords_list)
    for r in d:
      for n in r['index']:
        keywords_list.append([r['album_name']])

      print(keywords_list)

"""Sorting algorithms"""

#sorting algorithms
import sys
sys.setrecursionlimit(3000)
import time
import random
#bubblesort

def bubblesort(keywords_list):
  for i in range(0, len(keywords_list)):
    for j in range(0,len(keywords_list) - 1):
      if keywords_list[j] [0] > keywords_list[j+1][0]:
        temp = keywords_list[j] + keywords_list [j+1]
        keywords_list[j+1] = temp

bubblesort(keywords_list)
print(keywords_list)

#insertion sort

def insertionsort(keywords_list):
  for i in range(0,len(keywords_list)):
    j = i
    while(j > 0 and keywords_list[j-1][0] > keywords_list[j][0]):
      temp = keywords_list[j]
      keywords_list[j] = keywords_list[j-1]
      keywords_list[j-1] = temp
      j = j-1

insertionsort(keywords_list)
print(keywords_list)

#quick sort

def partition(keywords_list, low, high):
  pivot = keywords_list[high]
  index = low

  for i in range(low, high):
    if keywords_list[i] <= pivot:
      temp = keywords_list[index]
      keywords_list[index] = keywords_list[i]
      keywords_list[i] = temp
      index = index + 1

  temp = keywords_list[high]
  keywords_list[high] = keywords_list[index]
  keywords_list[index] = temp

  return index

def qsort(keywords_list, low, high):
  if low < high:
    pivot = partition(keywords_list, low, high)

    qsort(keywords_list, low, pivot - 1);
    qsort(keywords_list, pivot + 1, high);

def quicksort(keywords_list):
    qsort(keywords_list, 0, len(keywords_list) - 1)

quicksort(keywords_list)
print(keywords_list)

#merge sort

def mergeSort(keywords_list):
    if len(keywords_list) > 1:
        mid = len(keywords_list) // 2
        left = keywords_list[:mid]
        right = keywords_list[mid:]

        mergeSort(left)
        mergeSort(right)

        i = 0
        j = 0
        k = 0

        while i < len(left) and j < len(right):
            if left[i] <= right[j]:
              keywords_list[k] = left[i]
              i += 1
            else:
                keywords_list[k] = right[j]
                j += 1
            k += 1

        while i < len(left):
            keywords_list[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            keywords_list[k]=right[j]
            j += 1
            k += 1

mergeSort(keywords_list)
print(keywords_list)

start = time.time ()
albums = bubblesort(keywords_list)
end = time.time()
print(f"Bubble Sort: {(end - start)} seconds")
start = time.time()
albums = insertionsort(keywords_list)
end = time.time()
print(f"Insertion sort takes: {(end - start)} seconds")
start = time.time()
albums = quicksort(keywords_list)
end = time.time()
print(f"Quick sort takes: {(end - start)} seconds")
print(keywords_list)
start = time.time()
albums = mergeSort(keywords_list)
end = time.time()
print(f"Merge sort takes: {(end - start)} seconds")

print(keywords_list)

"""Searches"""

#binary search
def binary_search(keywords_list,low, high, search):
  while low <= high:
    mid = low + (high - low)// 2

    if keywords_list[mid][0] == search:
      return mid
    elif keywords_list[mid][1] < search:
      return binary_search(keywords_list, low, mid -1, search)
    else:
      return binary_search(keywords_list, mid + 1, high, search)
  return -1
  print(binary_search(keywords_list, 0, len(keywords_list) -1, search))

def sequential_search (keywords_list, search):
  for i in range (0, len (keywords_list)):
    if search == keywords_list[i]:
      return i
  else:
    return False
  print (sequential_search(keywords_list, search))

albums = ["Midnights (3am Edition).jpg", "Red (Taylor's Version).jpg","Fearless (Taylor's Version).jpg", "evermore(deluxe version).jpg", "folklore: the long pond studio sessions (from the Disney+ special)[deluxe edition].jpg", "folklore (deluxe version)" ,"Lover.jpg", "Taylor Swift Karaoke: reputation.jpg"]

!pip install ipyplot
from IPython.display import Image
import ipyplot
import numpy

#@title Taylor Swift Discography {run: "auto"}
#@markdown <p align = "center"> Taylor Swift Discography</p>
#@markdown <p align = "center"> <img src = https://upload.wikimedia.org/wikipedia/en/3/33/The_Eras_Tour_poster.jpg> </p>
#@ <br>

search = "Taylor Swift" #@param {type:"string"}
list_albums = ["Midnights (3am Edition).jpg", "Red (Taylor's Version).jpg","Fearless (Taylor's Version).jpg","evermore (deluxe version).jpg", "folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition].jpg", "folklore (deluxe version)" ,"Lover.jpg", "Taylor Swift Karaoke: reputation.jpg"]
list_albums.append(album_img)

if albums[-4:] != ".jpg":
  album_name = album_name + ".jpg"

index = binary_search(keywords_list, 0, len(list_albums), search)
albums = keywords_list[index][1]

if len(list_albums) > 0:
  ipyplot.plot_images(list_albums, max_images=10, img_width=150, force_b64=False)
  print(album_name)